export enum PaymentStatus {
    INITIALIZED = 'INITIALIZED',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    FAILED_PAYMENT = 'FAILED_PAYMENT',
    FAILED_CHECKOUT = 'FAILED_CHECKOUT',
}
