export enum PaymentProcessorType {
  BRAINTREE_PAYPAL = 'BRAINTREE_PAYPAL',
  BRAINTREE_VENMO = 'BRAINTREE_VENMO',

  APPLE_PAY_ELAVON = 'APPLE_PAY_ELAVON',
  APPLE_PAY_FREEDOM_PAY = 'APPLE_PAY_FREEDOM_PAY',

  CARD_ELAVON = 'CARD_ELAVON',
  CARD_FREEDOM_PAY = 'CARD_FREEDOM_PAY',

  CARD_STRIPE = 'CARD_STRIPE',

  GIFT_VOUCHER = 'GIFT_VOUCHER',
  MILITARY_VOUCHER = 'MILITARY_VOUCHER',
  INVOICE_VOUCHER = 'INVOICE_VOUCHER',

  CASH = 'CASH',
  MANUAL_CASH = 'MANUAL_CASH',

  UNITED_MILES = 'UNITED_MILES',

  ICOUPON = 'ICOUPON',

  NO_OP = 'NO_OP',

  OTG_INTERNAL_PO = 'OTG_INTERNAL_PO',
}
